[2024-09-25T06:18:33.015+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paginated_api_to_csv_with_dag_params.fetch_paginated_api_data manual__2024-09-25T06:18:32.065531+00:00 [queued]>
[2024-09-25T06:18:33.025+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paginated_api_to_csv_with_dag_params.fetch_paginated_api_data manual__2024-09-25T06:18:32.065531+00:00 [queued]>
[2024-09-25T06:18:33.025+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2024-09-25T06:18:33.039+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fetch_paginated_api_data> on 2024-09-25 06:18:32.065531+00:00
[2024-09-25T06:18:33.043+0000] {standard_task_runner.py:57} INFO - Started process 1542 to run task
[2024-09-25T06:18:33.046+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'paginated_api_to_csv_with_dag_params', 'fetch_paginated_api_data', 'manual__2024-09-25T06:18:32.065531+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/common_authentication_data_pipeline.py', '--cfg-path', '/tmp/tmpyu96rbyd']
[2024-09-25T06:18:33.047+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask fetch_paginated_api_data
[2024-09-25T06:18:33.084+0000] {task_command.py:410} INFO - Running <TaskInstance: paginated_api_to_csv_with_dag_params.fetch_paginated_api_data manual__2024-09-25T06:18:32.065531+00:00 [running]> on host 8b877ad46059
[2024-09-25T06:18:33.134+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='paginated_api_to_csv_with_dag_params' AIRFLOW_CTX_TASK_ID='fetch_paginated_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T06:18:32.065531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T06:18:32.065531+00:00'
[2024-09-25T06:18:34.588+0000] {logging_mixin.py:150} INFO - Total records to fetch: 7714
[2024-09-25T06:18:34.588+0000] {logging_mixin.py:150} INFO - Total requests required: 1
[2024-09-25T06:18:35.911+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/common_authentication_data_pipeline.py", line 108, in fetch_data_and_save
    os.makedirs(OUTPUT_DIR, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/path'
[2024-09-25T06:18:35.929+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=paginated_api_to_csv_with_dag_params, task_id=fetch_paginated_api_data, execution_date=20240925T061832, start_date=20240925T061833, end_date=20240925T061835
[2024-09-25T06:18:35.942+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 12 for task fetch_paginated_api_data ([Errno 13] Permission denied: '/path'; 1542)
[2024-09-25T06:18:35.954+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-09-25T06:18:35.970+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
